### PR TITLE
fix(discovery): improve covers discovery

### LINKED ISSUE #3862: shutter recognized as dimmer
Dear all,

i connected the homeassistant to zwave-js-ui.
made working with mqtt discovery because of issues that the shutter is recognized as dimmier
once i made the choice i can see home assistant option on the device.
but the device reporting also as dimmer:
{
  "type": "light",
  "object_id": "dimmer_9",
  "discovery_payload": {
    "command_topic": "zwave/lab/gp9/switch_multilevel/endpoint_9/targetValue/set",
    "state_topic": "zwave/lab/gp9/switch_multilevel/endpoint_9/currentValue",
    "state_value_template": "{{ \"OFF\" if value_json.value == 0 else \"ON\" }}",
    "brightness_command_topic": "zwave/lab/gp9/switch_multilevel/endpoint_9/targetValue/set",
    "brightness_scale": 99,
    "brightness_state_topic": "zwave/lab/gp9/switch_multilevel/endpoint_9/currentValue",
    "brightness_value_template": "{{ value_json.value }}",
    "on_command_type": "brightness",
    "availability": [
      {
        "payload_available": "true",
        "payload_not_available": "false",
        "topic": "zwave/lab/gp9/status",
        "value_template": "{{'true' if value_json.value else 'false'}}"
      },
      {
        "topic": "zwave/_CLIENTS/ZWAVE_GATEWAY-zwave-js-ui/status",
        "value_template": "{{'online' if value_json.value else 'offline'}}"
      },
      {
        "payload_available": "true",
        "payload_not_available": "false",
        "topic": "zwave/driver/status"
      }
    ],
    "availability_mode": "all",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xf2e08abf_node48"
      ],
      "manufacturer": "TouchWand Co., Ltd.",
      "model": "Glass 9 v2.03 (Glass9)",
      "name": "lab-gp9",
      "sw_version": "4.13.8"
    },
    "name": "lab-gp9_dimmer_9",
    "unique_id": "zwavejs2mqtt_0xf2e08abf_48-38-9-currentValue"
  },
  "discoveryTopic": "light/lab-gp9/dimmer_9/config",
  "values": [
    "38-9-currentValue",
    "38-9-targetValue"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "light_dimmer_9"
}

is there anything i can do to make it work as shutter?
are there any automation for making all dimmer recognized as shutter?

zeev

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #3862

### CODE REVIEW

File: api/lib/Gateway.ts [hunk 1]
```diff
@@ -1270,6 +1270,7 @@ export default class Gateway {
 								'specific_type_class_b_motor_control',
 								'specific_type_class_c_motor_control',
 								'specific_type_class_motor_multiposition',
+								'specific_type_motor_multiposition',
```
Comment (zeev-mindali) [inline api/lib/Gateway.ts:1273]: the missing type for some zwave devices
