### PR TITLE
fix(ui): show nlwr route when lwr is unknown in overview

### LINKED ISSUE #3563: Sometimes battery devices reported as "Unconnected" in the network map
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.8.1.04f1c76

### ZwaveJS version

12.4.3

### Describe the bug

Sometimes after restarting Z-Wave JS UI, the network map shows devices as unconnected.

image

If you zoom into the node, it shows the NLWR but shows the connection.

image

Note that 19 and 11 are battery devices. When you open the network map, ZUI queries the driver and asks the controller for route information. In the case of these two nodes, they only report NLWR, not LWR:

```text
3982   │ Jan 27 14:42:38 zui[3592858]: 14:42:38.863 SERIAL » 0x0105009200137b                                                     (7 bytes)
3983   │ Jan 27 14:42:38 zui[3592858]: 14:42:38.863 DRIVER » [REQ] [GetPriorityRoute]
3984   │ Jan 27 14:42:38 zui[3592858]:                         node ID: 19
3985   │ Jan 27 14:42:38 zui[3592858]: 14:42:38.871 SERIAL « [ACK]                                                                   (0x06)
3986   │ Jan 27 14:42:38 zui[3592858]: 14:42:38.873 SERIAL « 0x010b0192001302000000000375                                        (13 bytes)
3987   │ Jan 27 14:42:38 zui[3592858]: 14:42:38.873 SERIAL » [ACK]                                                                   (0x06)
3988   │ Jan 27 14:42:38 zui[3592858]: 14:42:38.874 DRIVER « [RES] [GetPriorityRoute]
3989   │ Jan 27 14:42:38 zui[3592858]:                         node ID:     19
3990   │ Jan 27 14:42:38 zui[3592858]:                         route kind:  NLWR
3991   │ Jan 27 14:42:38 zui[3592858]:                         repeaters:   none
3992   │ Jan 27 14:42:38 zui[3592858]:                         route speed: 100k
```

The same is for Node 11. A working battery node like 12 reports LWR:

```text
3950   │ Jan 27 14:42:38 zui[3592858]: 14:42:38.825 DRIVER » [REQ] [GetPriorityRoute]
3951   │ Jan 27 14:42:38 zui[3592858]:                         node ID: 12
3952   │ Jan 27 14:42:38 zui[3592858]: 14:42:38.831 SERIAL « [ACK]                                                                   (0x06)
3953   │ Jan 27 14:42:38 zui[3592858]: 14:42:38.832 SERIAL « 0x010b0192000c010e0000000367                                        (13 bytes)
3954   │ Jan 27 14:42:38 zui[3592858]: 14:42:38.832 SERIAL » [ACK]                                                                   (0x06)
3955   │ Jan 27 14:42:38 zui[3592858]: 14:42:38.833 DRIVER « [RES] [GetPriorityRoute]
3956   │ Jan 27 14:42:38 zui[3592858]:                         node ID:     12
3957   │ Jan 27 14:42:38 zui[3592858]:                         route kind:  LWR
3958   │ Jan 27 14:42:38 zui[3592858]:                         repeaters:   14
3959   │ Jan 27 14:42:38 zui[3592858]:                         route speed: 100k
```

Not sure why that's the case. Anyways, ZUI will display those nodes as "Unconnected" until a LWR route is reported. This is little misleading because the devices are reporting fine. Note that since these are battery devices a LWR route won't be available at minimum until the device wakes up.

If I understand correctly, the code the populates the nodes and edges 1) checks for a LWR route, if not found it colors the node grey and makes no connections 2) then checks for a NLWR and skips updating the node color and edges if on the overview page.

### To Reproduce

Restart ZUI and enter the network map page. The controller must report some battery devices' routes as NLWR.

### Expected behavior

Not sure what is better. Maybe the overview page can show the NLWR dotted-line edge in case the LWR is missing?

Should it color the node based on the NLWR route? Both of the nodes in this example are one hop away with the NLWR.

### Additional context

Related to https://github.com/zwave-js/zwave-js-ui/issues/3562. Fixing that might also fix this or vice-versa.

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #3563

### CODE REVIEW

**Comment by robertsLando** [comment]
@kpine could you test this and tell me if it's working?

**Comment by robertsLando** [comment]
Use `test2` tag once this ends: https://github.com/zwave-js/zwave-js-ui/actions/runs/7801920120

File: src/components/custom/ZwaveGraph.vue [hunk 1]
```diff
@@ -1196,6 +1204,7 @@ export default {
 					entity,
 					node.statistics?.nlwr,
 					RouteKind.NLWR,
+					!!node.statistics?.lwr,
```
Comment (robertsLando) [inline src/components/custom/ZwaveGraph.vue:1207]: @kpine in fact, I have added a duplicated `!` here, that's a typo

```suggestion
					!node.statistics?.lwr,
```
